from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 879)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphic_Viewer = QtWidgets.QGraphicsView(Form)
        self.graphic_Viewer.setObjectName("graphic_Viewer")
        self.horizontalLayout.addWidget(self.graphic_Viewer)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(251, 531))
        self.widget.setMaximumSize(QtCore.QSize(251, 531))
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 251, 20))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Equation1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.ln_shower = QtWidgets.QCheckBox(self.widget)
        self.ln_shower.setEnabled(True)
        self.ln_shower.setGeometry(QtCore.QRect(160, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(16)
        self.ln_shower.setFont(font)
        self.ln_shower.setObjectName("ln_shower")
        self.acceptButton = QtWidgets.QPushButton(self.widget)
        self.acceptButton.setGeometry(QtCore.QRect(0, 490, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(20)
        self.acceptButton.setFont(font)
        self.acceptButton.setObjectName("acceptButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 290, 241, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.times_Adder = QtWidgets.QPushButton(self.widget)
        self.times_Adder.setGeometry(QtCore.QRect(140, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(16)
        self.times_Adder.setFont(font)
        self.times_Adder.setObjectName("times_Adder")
        self.arg2_Inputer = QtWidgets.QLineEdit(self.widget)
        self.arg2_Inputer.setGeometry(QtCore.QRect(0, 130, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.arg2_Inputer.setFont(font)
        self.arg2_Inputer.setObjectName("arg2_Inputer")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(0, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(0, 450, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Equation2.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(140, 490, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(20)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.times_selector = QtWidgets.QSpinBox(self.widget)
        self.times_selector.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.times_selector.setFont(font)
        self.times_selector.setObjectName("times_selector")
        self.arg1_Inputer = QtWidgets.QLineEdit(self.widget)
        self.arg1_Inputer.setGeometry(QtCore.QRect(0, 50, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.arg1_Inputer.setFont(font)
        self.arg1_Inputer.setObjectName("arg1_Inputer")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.logBrowser = QtWidgets.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("FZMiaoWu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logBrowser.setFont(font)
        self.logBrowser.setObjectName("logBrowser")
        self.gridLayout.addWidget(self.logBrowser, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.exitButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Input Arg2:"))
        self.ln_shower.setText(_translate("Form", "Show"))
        self.acceptButton.setText(_translate("Form", "Accept"))
        self.times_Adder.setText(_translate("Form", "Add"))
        self.arg2_Inputer.setText(_translate("Form", "0.89, 0.91, 0.94, 0.96, 0.99, 1.0, 1.03, 1.06, 1.08, 1.11, 1.14, 1.16, 1.18, 1.2"))
        self.label_8.setText(_translate("Form", "Fitting Type:"))
        self.exitButton.setText(_translate("Form", "Exit"))
        self.arg1_Inputer.setText(_translate("Form", "450, 500, 560, 630, 710, 800, 900, 1000, 1120, 1250, 1400, 1600, 1800, 2000"))
        self.label_10.setText(_translate("Form", "Input Arg1:"))
        self.logBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FZMiaoWu\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:400;\"><br /></p></body></html>"))